name: Bug report
description: '`mime` support'

body:
  - type: checkboxes
    attributes:
      label: Idiot Checks™
      options:
        - label: This is NOT about a specific MIME type⬌extension.  Concerns with specific MIME types should be addressed in [the `mime-db` project](https://github.com/jshttp/mime-db/issues).  (Be sure to search the issues first.  Odds are good your concern has already been reported.)
          required: true
        - label: The title (above) is descriptive and specific to my problem (i.e. search-engine friendly)
          required: true
        - label: I know what an "MRE" is and will provide one below.  (Not sure what an MRE is?  (Read this)[https://stackoverflow.com/help/minimal-reproducible-example])
          required: true

  - type: input
    attributes:
      label: MRE (link)
      description: URL to an MRE demonstrating your problem.  Ideally, this is a project on https://stackblitz.com/. https://codepen.io and https://codesandbox.io/ are good alternatives.  A github repo also works but is not ideal.  Not sure where to start?  Click "Fork" on https://stackblitz.com/edit/mime-sample-mre?file=index.js
      placeholder: E.g. https://stackblitz.com/edit/mime-sample-mre?file=index.js

  - type: textarea
    attributes:
      label: MRE (supporting details)
      description: Okay, we've opened your MRE link... now what?
      value: |
        Actual behavior:  ...
        Expected behavior: ...

  - type: textarea
    attributes:
      label: "Actually, Let me just tell you about my problem ..."
      description: |
        This is a trap.  Putting anything here means you're doing it wrong and this issue will be closed without comment. 😈
