name: Bug report
description: '`mime` support'

body:
  - type: checkboxes
    attributes:
      label: Sanity Checks
      options:
        - label: This is NOT about a specific MIME type⬌extension mapping.  Such concerns should be addressed in [the `mime-db` project](https://github.com/jshttp/mime-db/issues).  (Be sure to search the issues first.  Odds are good your concern has already been reported.)
          required: true
        - label: Your issue title is descriptive and specific to the problem (i.e. search-engine friendly)
          required: true
        - label: You understand what an "MRE" is, and why providing one is important.  (If not, [read this](https://stackoverflow.com/help/minimal-reproducible-example))
          required: true

  - type: input
    attributes:
      label: MRE (link)
      description: URL to MRE demonstrating the problem.  Ideally, this is a project on [StackBlitz](https://stackblitz.com/). [Codepen](https://codepen.io) and [CodeSandbox](https://codesandbox.io) are good alternatives.  A github repo also works but is not ideal.  Not sure where to start?  Here's [a StackBlitz template](https://stackblitz.com/edit/mime-sample-mre?file=index.js).
      placeholder: E.g. https://stackblitz.com/edit/mime-sample-mre?file=index.js

  - type: textarea
    attributes:
      label: MRE (supporting details)
      description: '"Okay, we''ve opened your MRE link... now what?"'
      value: |
        Actual behavior:  ...
        Expected behavior: ...

  - type: textarea
    attributes:
      label: '"Actually, let me just tell you about my problem instead ..."'
      description: |
        This is a trap.   You can fill this out if you're feeling adventurous but issues that omit an MRE are likely to be closed without comment.
