name: Bug report
description: '`mime` support'

body:
  - type: checkboxes
    attributes:
      label: Idiot Checks&tm;
      options:
        - label: This is NOT about a specific MIME type &harr; extension.  If it is, please search [the mime-project issues](https://github.com/jshttp/mime-db/issues).  That's what this project uses, and there's a 99% chance your issue has already been raised there.
          required: true
        - label: The issue title is descriptive and specific to your problem (i.e. search-engine friendly)
          required: true
        - label: I know what an "MRE" is.  If not, (read this)[https://stackoverflow.com/help/minimal-reproducible-example]"
          required: true

  - type: input
    attributes:
      label: MRE (link)
      description: URL to an MRE demonstrating your problem.  This should be a project on StackBlitz, Codepen, or maybe CodeSandbox.  A github repo is also acceptable, but not ideal.  If you need a starting point, here's (a forkable-project on StackBlitz)[https://stackblitz.com/edit/mime-sample-mre?file=index.js]
      placeholder: E.g. https://stackblitz.com/edit/mime-sample-mre?file=index.js

  - type: textarea
    attributes:
      label: MRE (supporting details)
      description: Okay, I've opened your MRE link.  Now what?
      value: |
        Actual behavior:  ...
        Expected behavior: ...

  - type: textarea
    attributes:
      label: 'Actually, let me just tell you about my problem ...'
      description: |
        This is a trap.  If you need to use this field you're doing it wrong and this issue will be closed without comment.
